spring:
  datasource:
    url: jdbc:mysql://localhost:12345/jj_novel
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

  profiles:
      active: dev
      include: website,alipay,oss,fastdfs

